spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/baedal
    username: choose
    password: 1234
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: