spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/baedal
    username: choose
    password: 1234
  data:
    redis:
      host: localhost
      port: 63790
      username: default
      password:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true # sql 로깅
        format_sql: true # SQL 문 정렬하여 출력
        highlight_sql: true # SQL 문 색 부여
        use_sql_comments: true # 콘솔에 표시되는 쿼리문 위에 어떤 실행을 하려는지 HINT 표시
  #        generate_statistics: true # 쿼리수행 통계
  docker:
    compose:
      lifecycle-management: start-and-stop # 스프링 실행 시 컴포즈 실행하고, 종료 시 함께 종료
      start:
        command: up
      stop:
        command: down
        timeout: 1m

jwt:
  secret:
    key: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==
ai:
  api:
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent
    key: "${AI_API_KEY}"