spring:
  application:
    name: baedal
  profiles:
    default: dev
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true # sql 로깅
        format_sql: true # SQL 문 정렬하여 출력
        highlight_sql: true # SQL 문 색 부여
        use_sql_comments: true # 콘솔에 표시되는 쿼리문 위에 어떤 실행을 하려는지 HINT 표시
  #        generate_statistics: true # 쿼리수행 통계